version: "3.9"  # optional since v1.27.0
services:
  iis_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: .\DynamicSite
        target: C:\inetpub\wwwroot\
  iisbase_web:
    image: iisbase_image
    ports:
      - "8090:80"